name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    env:
      Solution_Name: Client\Puyo-Puyo-Tetris-Archipelago.sln
      Test_Project_Path: Client\UnitTests\UnitTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --no-restore -c ${{ matrix.configuration }}

    - name: Test
      run: >
        dotnet test $env:Solution_Name --no-build -c ${{ matrix.configuration }}
        --logger "trx;LogFileName=test-results.trx"
        --collect:"Code Coverage;Format=cobertura"
        --results-directory TestResults

    - name: Upload test results & coverage
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults

    - name: Publish
      run: >
        dotnet publish Client\Puyo-Puyo-Tetris-Archipelago\Puyo-Puyo-Tetris-Archipelago.csproj
        -c ${{ matrix.configuration }}
        -r win-x64 --self-contained true
        -p:DebugType=portable -p:DebugSymbols=true
        -o publish

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: Puyo-Puyo-Tetris-Archipelago-win-x64
        path: publish